cmake_minimum_required(VERSION 3.28)

set(CMAKE_CXX_FLAGS_DEBUGSERVER "${CMAKE_CXX_FLAGS_DEBUG} -DSERVER=1")
set(CMAKE_C_FLAGS_DEBUGSERVER "${CMAKE_C_FLAGS_DEBUG} -DSERVER=1")
set(CMAKE_EXE_LINKER_FLAGS_DEBUGSERVER "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -DSERVER=1")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUGSERVER "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} -DSERVER=1")

set(CMAKE_CXX_FLAGS_MINSIZERELSERVER "${CMAKE_CXX_FLAGS_MINSIZEREL} -DSERVER=1")
set(CMAKE_C_FLAGS_MINSIZERELSERVER "${CMAKE_C_FLAGS_MINSIZEREL} -DSERVER=1")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZERELSERVER "${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL} -DSERVER=1")
set(CMAKE_SHARED_LINKER_FLAGS_MINSIZERELSERVER "${CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL} -DSERVER=1")
